<?php

namespace Videona\DBBundle\Entity;

/**
 * AuthCodeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AuthCodeRepository extends \Doctrine\ORM\EntityRepository
{
}
