<?php

namespace Videona\DBBundle\Entity;

/**
 * SocialGoogleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialGoogleRepository extends \Doctrine\ORM\EntityRepository
{
}
