<?php

namespace Videona\DBBundle\Entity;

/**
 * SocialTwitterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialTwitterRepository extends \Doctrine\ORM\EntityRepository
{
}
