<?php

namespace Videona\DBBundle\Entity;

/**
 * SocialFacebookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialFacebookRepository extends \Doctrine\ORM\EntityRepository
{
}
