<?php

namespace Videona\DBBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SocialTwitterRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialTwitterRepository extends EntityRepository
{
}
