<?php

namespace Videona\DBBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SocialFacebookRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SocialFacebookRepository extends EntityRepository
{
    
    /* Para crear aquí querys generales que pueda llamar desde controladores
     * public function getTareas()
     * {
     * }
     */
    public function getPrueba()
    {
        ld('funciona??');
    }
    
}
