videona_backend_o_auth_homepage:
    path:     /hello/{name}
    defaults: { _controller: VideonaBackendOAuthBundle:Default:index }

oauth_server_auth_login:
    pattern:  /oauth/v2/auth_login
    defaults: { _controller: VideonaBackendOAuthBundle:Security:login }

oauth_server_auth_login_check:
    pattern:  /oauth/v2/auth_login_check
    defaults: { _controller: VideonaBackendOAuthBundle:Security:loginCheck }