security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
            #remember_me: true

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo

        api:  
            remember_me:
                key:      aSecretKey
                lifetime: 3600
                #path:     ~
                path:     /
                domain:   ~ 
#            remember_me:
#                key:      aSecretKey
#                lifetime: 3600
#                path:     ~
#                #path:     /
#                domain:   ~ 
#                # Defaults to the current domain from $_SERVER
            pattern: ^/api/.* 
            #provider: fos_userbundle
#            remember_me:
#                key:      aSecretKey
#                lifetime: 3600
#                path:     /
#                domain:   ~ # Defaults to the current domain from $_SERVER
            form_login: false
            http_basic:  
              #remember_me: true
              realm: "REST Service Realm" 
              provider: fos_userbundle
              
#            remember_me:
#                token_provider: name
#                key: someS3cretKey
#                name: NameOfTheCookie
#                lifetime: 3600 # in seconds
#                path: /api
#                domain: somedomain.foo
#                secure: false
#                httponly: true
#                always_remember_me: false
#                remember_me_parameter: _remember_me
#            remember_me:
#                key: 'some-unique-key'
#                remember_me_parameter: 'login[remember_me]'
            logout:
                path:   /api/logout
                target: /api/logout-success
#            remember_me:
#                key: "aSecretKey"
#                lifetime: 604800
#            remember_me:
#                #key: "%key%"
#                key: "ProBandO"
#                lifetime: 31536000 
#                # 365 days in seconds
#                #name: RememberMe
#                #path: /api/
#                path: /
#                domain: ~ 
#                # Defaults to the current domain from $_SERVER
#                #remember_me_parameter: _remember_me
#                always_remember_me: true
            security:  true  
            stateless: false  
            anonymous: ~
                            
        main:
            pattern: ^/
            remember_me:
                key:      "aSecretKey"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                #login_path: /login
                #check_path: /login_check
                #default_target_path: /donde yo quiera
            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                    twitter: "/login/check-twitter"
                login_path: /login
                use_forward: false
                failure_path: /login
                default_target_path: /register/username
                oauth_user_provider:
                #this is my custom user provider, created from FOSUBUserProvider - will manage the
                #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider
            logout:       true
            anonymous:    true
            security: true
            http_basic: ~
                    
    access_control:
        #Backend
        - { path: ^/api/signup, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/logout-success, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/check-user, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, role: ROLE_USER }
        
        #Frontend
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }