security:
    encoders:
        #Symfony\Component\Security\Core\User\User: plaintext
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email

    firewalls:
        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        demo_login:
            pattern:  ^/demo/secured/login$
            security: false

        demo_secured_area:
            pattern:    ^/demo/secured/
            form_login:
                check_path: _demo_security_check
                login_path: _demo_login
            logout:
                path:   _demo_logout
                target: _demo

        api:
            pattern: ^/api/.* 
            form_login: false
            http_basic:  
                realm: "REST Service Realm" 
                provider: fos_userbundle
            logout:
                path:   /api/logout
                target: /api/logout-success
            security:  true  
            stateless: false
            anonymous: ~
                            
        main:
            pattern: ^/
            remember_me:
                key:      "%remember_me_key%"
                lifetime: 31536000 # 365 days in seconds
                path:     /
                domain:   ~ # Defaults to the current domain from $_SERVER
            form_login:
                provider: fos_userbundle
                csrf_provider: form.csrf_provider
                remember_me: true
                #login_path: /login
                #check_path: /login_check
                #default_target_path: /donde yo quiera
            oauth:
                resource_owners:
                    facebook: "/login/check-facebook"
                    google: "/login/check-google"
                    twitter: "/login/check-twitter"
                login_path: /login
                use_forward: false
                failure_path: /login
                default_target_path: /register/username
                oauth_user_provider:
                #this is my custom user provider, created from FOSUBUserProvider - will manage the
                #automatic user registration on your site, with data from the provider (facebook. google, etc.)
                    service: my_user_provider
            logout:       true
            anonymous:    true
            security: true
            http_basic: ~
                    
    access_control:
        #Backend
        - { path: ^/api/signup, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/logout-success, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/check-user, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/prueba, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/, role: ROLE_USER }
        
        #Frontend
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        #- { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/login, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin/, role: ROLE_ADMIN }