parameters:
#    videona_backend_social.example.class: Videona\Backend\SocialBundle\Example
    my_facebook_manager.class:       Videona\Backend\SocialBundle\Services\FacebookManager
    my_google_manager.class:       Videona\Backend\SocialBundle\Services\GoogleManager
    my_twitter_manager.class:       Videona\Backend\SocialBundle\Services\TwitterManager
    my_image_manager.class:       Videona\Backend\SocialBundle\Services\ImageManager

services:
#    videona_backend_social.example:
#        class: %videona_backend_social.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
    my_facebook_manager:
        class: %my_facebook_manager.class%
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            imageManager: "@my_image_manager"
            
    my_google_manager:
        class: %my_google_manager.class%
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            imageManager: "@my_image_manager"
            
    my_twitter_manager:
        class: %my_twitter_manager.class%
        arguments:
            entityManager: "@doctrine.orm.entity_manager"
            imageManager: "@my_image_manager"
            
    my_image_manager:
        class: %my_image_manager.class%
        arguments:
            entityManager: "@doctrine.orm.entity_manager"